### ISSUE TITLE
multistation bug  doing test

### ISSUE THREAD

**Issue by markmac99** [markmac99/ukmon-pitools#37]
filenotfound error while running test
test successful
Traceback (most recent call last):
  File "/home/mark/source/ukmon-pitools-uk0006/sendToLive.py", line 141, in <module>
    singleUpload(sys.argv[1], sys.argv[2])
  File "/home/mark/source/ukmon-pitools-uk0006/sendToLive.py", line 132, in singleUpload
    os.remove('/tmp/test.txt')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/test.txt'
test successful

**Comment by markmac99** [comment]
Fixed by putting a try/except block round the os.remove() statement.
