### ISSUE TITLE
Refreshtools crashes with old image

### ISSUE THREAD

**Issue by markmac99** [markmac99/ukmon-pitools#48]
If using hte original UKMON RMS image, refreshtools crashes.
Traceback (most recent call last):
  File "/home/pi/source/ukmon-pitools/sendToLive.py", line 192, in <module>
    singleUpload(sys.argv[1], sys.argv[2])
  File "/home/pi/source/ukmon-pitools/sendToLive.py", line 144, in singleUpload
    rmscfg = inifvals['RMSCFG']
KeyError: 'RMSCFG'

This is because the RMSCFG variable isn't being set in the old config file, and i am no longer overwriting it!

**Comment by markmac99** [comment]
Workaround is to manually add
export RMSCFG=~/source/RMS/.config
to the file
I've also set a try/except block and set a default if its missing.
